### ISSUE TITLE
Clarification on Deeplab Model Configuration and Pre-training

### ISSUE THREAD

**Issue by cskyl** [linyq2117/CLIP-ES#10]
Hi,
Thank you for sharing your research and codebase with the community. I'm currently working on replicating the results and have a query regarding the Deeplab model's setup.
In your repository, it's mentioned that your Deeplab training code is adapted from [deeplab-pytorch](https://github.com/kazuto1011). I wanted to clarify if you strictly adhered to the default Pascal VOC configuration settings provided in that original repository. Additionally, did you utilize the pre-trained model (pretrained on COCO) that the repo offers, or did you employ a different configuration or pre-trained models for your experiments?

Thank you for your time and assistance!

**Comment by linyq2117** [comment]
Hi, thanks for your interest,

We provide the detailed setting in our paper (Appendix D). You can also find more details in this [issue](https://github.com/linyq2117/CLIP-ES/issues/7#issuecomment-1554728146).

**Comment by cskyl** [comment]
Hi,
Thank you for pointing me in the right direction. I'll review Appendix in your paper and the mentioned issue for further details. I appreciate your prompt response.

Best regards,
TC
________________________________
