### ISSUE TITLE
Problem with the link for train_aug groundtruth

### ISSUE THREAD

**Issue by masihnajafi02** [linyq2117/CLIP-ES#19]
Hi
I hope you're doing fine.
I wanted to point out that the link to train_aug groundtruth file for running the model on PascalVoc dataset redirects to Prof. Bharath Hariharan's homepage. Could you please help me get the train_aug groundtruth file in any other way?
Thanks a lot

**Comment by linyq2117** [comment]
Thanks for pointing out this problem. The train_aug ground-truth file can be found in [Dropbox](https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0).
