### ISSUE TITLE
about the performance

### ISSUE THREAD

**Issue by halbielee** [linyq2117/CLIP-ES#2]
Thanks for sharing the great work. I have a question for the performance.

When I runned the provided code and got pseudo-masks(CAM, etc), the performance is different from the reported. 

It shows 70.71 mIoU. I think the number should not be changed because the CLIP model is fixed.
Is there any difference between the one you reported and the other you shared?

By the way, thanks for sharing the code!

**Comment by linyq2117** [comment]
Hi, thanks for your attention to our work.

I run the code again and get 70.82 mIoU. The generated CAMs seem to have no problem. Did you strictly follow the commands in README? If so, the slight difference may stem from the version of some packages.
