### ISSUE TITLE
Thanks for you work, could you provide the setting of training Deeplabv2 on COCO dataset?

### ISSUE THREAD

**Issue by henry189** [linyq2117/CLIP-ES#20]

**Comment by linyq2117** [comment]
Hi, thanks for your interest,

We provide the detailed setting in our paper (Appendix D). You can also refer to this [issue](https://github.com/linyq2117/CLIP-ES/issues/7#issuecomment-1554728146) for more details.

**Comment by linyq2117** [comment]
Closed for inactivity.
