### ISSUE TITLE
COCO数据集的SegmentationClass文件

### ISSUE THREAD

**Issue by kalpa61** [linyq2117/CLIP-ES#21]
你好，请问COCO数据集的SegmentationClass文件该怎么获取，我在COCO官网上并没有找到这一文件，在搜索引擎上也没有找到答案，可以告知下吗，非常感谢！

**Comment by linyq2117** [comment]
Hi, thanks for your interest.

The SegmentationClass files of COCO can be obtained by converting COCO json file manually. We have provided the converted [file link](https://drive.google.com/file/d/1pRE9SEYkZKVg0Rgz2pi9tg48j7GlinPV/view) in README. Feel free to download it.

**Comment by kalpa61** [comment]
OK，非常感谢！
