### ISSUE TITLE
Can this model be trained?

### ISSUE THREAD

**Issue by NEO-237** [linyq2117/CLIP-ES#27]
I used CLIP-ES on my own dataset, but it didn't work very well for generatig CAMs. Is there any way to train this model to better fit my  dataset? Thanks.

**Comment by linyq2117** [comment]
Thanks for your interest!

CLIP-ES is based on the pre-trained CLIP model, which is a powerful foundation model trained on large-scale data and can apply to most common categories or scenarios. CLIP-ES is training-free and if your dataset is unique and uncommon, you may try the following ways: 1) carefully custome the text description for each category you used; 2) fine-tune the original CLIP model using your own data; 3) try other training-based WSSS methods.

**Comment by NEO-237** [comment]
Thanks a lot!
