### ISSUE TITLE
ReLU code

### ISSUE THREAD

**Issue by xd-429** [linyq2117/CLIP-ES#28]
I would like to ask whether the ReLU function is used in CAM generation, and where is the specific code?

**Comment by Link7808** [comment]
Line 144 in /pytorch_grad_cam `cam = np.maximum(cam, 0).astype(np.float32)#float16->32`
Line 152  in /pytorch_grad_cam `cam_per_target_layer = np.maximum(cam_per_target_layer, 0)`

**Comment by linyq2117** [comment]
Sorry for the late response. The answer is exactly as @Link7808  mentioned. Thanks for the explanation.
