### ISSUE TITLE
Clarification on COCO Dataset Segmentation Groundtruth

### ISSUE THREAD

**Issue by cskyl** [linyq2117/CLIP-ES#8]
Hello,
I've been exploring your repo and came across the COCO dataset segmentation ground truth. I observed that it's colored, and the pixel-level labels seem to be represented in multi-channels. I was wondering:
How this colored ground-truth was generated?
How do the colors in the segmentation gt correspond to class IDs?
Also, is there code here demonstrating how to evaluate COCO segmentation using this ground truth?
Thank you!

**Comment by linyq2117** [comment]
Hi, thanks for your interest!

You can use `Image.putpalette()` function in PIL to generate the colored mask, such as:
```
from PIL import Image
import numpy as np

im = Image.open("COCO2014/SegmentationClass/000000000009.png")
palette_coco = im.getpalette()

def colorful_coco(out, name, palette):
    arr = out.astype(np.uint8)
    im = Image.fromarray(arr)
    im.putpalette(palette)
    im.save(name)
```

The shape of the saved mask is (h, w) and represents class IDs for each pixel. It can be directly used for evaluation by reading with  `Image.open()`. The palette records color information for each class IDs and the multi-channels are not reflected on the output image. You can also manually set the  palette like [others.](https://github.com/tensorflow/models/blob/master/research/deeplab/utils/get_dataset_colormap.py)

**Comment by henry189** [comment]
Can you provide a link to the color palette that works with the COCO dataset?

**Comment by linyq2117** [comment]
You can get the color palette for COCO dataset from any COCO image:
```
im = Image.open("COCO2014/SegmentationClass/000000000009.png")
palette_coco = im.getpalette()
```
or you can refer to the palette used in other repository like [mmdetection](https://github.com/open-mmlab/mmdetection/blob/main/mmdet/datasets/coco.py).
